Feature 4 implement weekly messages
Metatavu/meta-assistant-lambda pull request #6
Opened 2022-03-09 09:25 UTC by Jdallos

2022-03-09 14:02 UTC, jarinykanen requested changes

2022-03-09 14:02 UTC, jarinykanen commented on serverless.ts
> +
```suggestion
```

2022-03-09 14:02 UTC, jarinykanen commented on src/features/future/weeklyBreakdown/formatWeeklyBreakdownData.ts
> +// import { FormattedTimebankData } from "@functions/schema";
Remove comments and fix the possible errors. Add comment why this code is not used

2022-03-09 14:02 UTC, jarinykanen commented on src/features/future/weeklyBreakdown/handlerFunctionsForBreakdown.ts
> +  //  const lastWeek = DateTime.now().minus({ days: 7 }).toISODate();
Remove comments and fix the possible errors. Add comment why this code is not used

2022-03-09 14:02 UTC, jarinykanen commented on src/features/future/weeklyBreakdown/weeklybreakdownmessage.ts
> +// import { WeeklyFormattedTimebankData } from "@functions/schema";
Remove comments and fix the possible errors. Add comment why this code is not used

2022-03-09 14:02 UTC, jarinykanen commented on src/features/generic/time-utils.ts
> +    }
```suggestion
    /**
     * Generates dates and numbers for previous week
     *
     * @returns various date formats/ numbers for start and end of previous week
     */
    export const lastWeekDateProvider = (): Dates => {
      const startOfWeek = DateTime.now().startOf("week");

      const weekStartDate = startOfWeek.minus({ weeks: 1 });
      const weekEndDate = startOfWeek.minus({ days: 1 });

      return { weekEndDate, weekStartDate };
    }
```

2022-03-09 14:02 UTC, jarinykanen commented on src/features/slackapi/slackapi-utils.ts
> +    const { name, logged, expected, date, project, internal, difference } = user;
```suggestion
    const { name, logged, expected, date, project, internal, difference } = user;

```

2022-03-09 14:02 UTC, jarinykanen commented on src/features/slackapi/slackapi-utils.ts
>          }
```suggestion
        client.chat.postMessage({
          channel: slackId,
          text: constructDailyMessage(user)
        });
      } catch (error) {
        console.error(`Error while posting slack messages to user ${user.name}`);
      }
```

2022-03-09 14:02 UTC, jarinykanen commented on src/features/slackapi/slackapi-utils.ts
> +        try {
Change to
```
      try {
        client.chat.postMessage({
          channel: slackId,
          text: constructWeeklySummaryMessage(user, weekStart, weekEnd)
        });
      } catch (error) {
        console.error(`Error while posting weekly slack messages to user ${user.name}`);
      }
```

2022-03-09 14:02 UTC, jarinykanen commented on src/features/timebank/timebank-API-provider.ts
> +   *
Missing description

2022-03-09 14:02 UTC, jarinykanen commented on src/features/timebank/timebank-API-provider.ts
> +  export const getTotalTimeEntries = async(duration: 'ALL_TIME' | 'YEAR' | 'MONTH' | 'WEEK', person: PersonDto, year: number, week: number): Promise<WeeklyCombinedData[]> => {
Create enum for duration

2022-03-09 14:02 UTC, jarinykanen commented on src/features/timebank/timebank-API-provider.ts
> +  }
```suggestion
  export const getTotalTimeEntries = async (duration: Duration, person: PersonDto, year: number, week: number): Promise<WeeklyCombinedData> => {
    try {
      const client = new TimebankApi(process.env.timebank_base_url);

      const { body } = await client.timebankControllerGetTotal(person.id.toString(), duration);
      const selectedWeek = body.filter(timePeriod => timePeriod.id.year === year && timePeriod.id.week === week)[0];

      const { firstName, lastName } = person;
      const combinedName = `${firstName} ${lastName}`;

      return { selectedWeek: selectedWeek, name: combinedName };
    } catch (error) {
      console.error("Error while loading total time entries");
      Promise.reject(error);
    }
  }
```

2022-03-09 14:02 UTC, jarinykanen commented on src/features/timebank/timebank-utils.ts
> +      if(length === 1){
```suggestion
      if (length === 1){
```

2022-03-09 14:02 UTC, jarinykanen commented on src/features/timebank/timebank-utils.ts
>    );
```suggestion
  export const combineWeeklyData = (timeData: WeeklyCombinedData[], slackUsers: Member[]): WeeklyCombinedData[] => (
    timeData.map(entry => {
      const slackUser = slackUsers.find(slackUser => slackUser.real_name === entry.name);

      return slackUser ? { ...entry, slackId: slackUser.id } : entry;
    })
  );
```

2022-03-09 14:02 UTC, jarinykanen commented on src/functions/schema.ts
> +
```suggestion
```

2022-03-09 14:02 UTC, jarinykanen commented on src/functions/sendWeeklyMessage/handler.ts
> +
```suggestion
```

2022-03-09 14:02 UTC, jarinykanen commented on src/functions/sendWeeklyMessage/handler.ts
> + * main function
```suggestion
 * Lambda for sending weekly messages
```

2022-03-09 14:02 UTC, jarinykanen commented on src/functions/sendWeeklyMessage/handler.ts
> +};
```suggestion
 * @param event API Gateway proxy event
 * @returns JSON response
 */
const sendWeeklyMessage: ValidatedEventAPIGatewayProxyEvent<typeof schema> = async (event: ValidatedAPIGatewayProxyEvent<typeof schema>) => {
  try {
    const timebankUsers = await TimeBankApiProvider.getTimebankUsers();
    const slackUsers = await SlackApiUtilities.getSlackUsers();

    const { weekStartDate, weekEndDate } = TimeUtilities.lastWeekDateProvider();
    const timeEntries: WeeklyCombinedData[] = [];

    for (const person of timebankUsers) {
      timeEntries.push(await TimeBankApiProvider.getTotalTimeEntries(Duration.WEEK, person, weekStartDate.year, weekEndDate.weekNumber));
    }

    const weeklyCombinedData = TimeBankUtilities.combineWeeklyData(timeEntries, slackUsers);

    SlackApiUtilities.postWeeklyMessage(weeklyCombinedData, weekStartDate.toISODate(), weekEndDate.toISODate());

    return formatJSONResponse({
      message: `Everything went well ${event.body.name}...`,
      event,
    });
  } catch (error) {
    return formatJSONResponse({
      message: `Error while sending slack message: ${error}`,
      event,
    });
  }
};

```

2022-03-09 14:02 UTC, jarinykanen commented on src/functions/index.ts
> +export { default as sendWeeklyMessage } from './sendWeeklyMessage';
```suggestion
export { default as sendDailyMessage } from "./sendDailyMessage";
export { default as sendWeeklyMessage } from "./sendWeeklyMessage";
```

2022-03-10 07:58 UTC, Jdallos commented on src/features/future/weeklyBreakdown/formatWeeklyBreakdownData.ts
> +// import { FormattedTimebankData } from "@functions/schema";
Done

2022-03-10 07:58 UTC, Jdallos commented on src/features/future/weeklyBreakdown/handlerFunctionsForBreakdown.ts
> +  //  const lastWeek = DateTime.now().minus({ days: 7 }).toISODate();
done

2022-03-10 07:59 UTC, Jdallos commented on src/features/future/weeklyBreakdown/weeklybreakdownmessage.ts
> +// import { WeeklyFormattedTimebankData } from "@functions/schema";
done

2022-03-10 08:13 UTC, Jdallos commented on src/features/slackapi/slackapi-utils.ts
> +        try {
done

2022-03-10 08:24 UTC, Jdallos commented on src/features/timebank/timebank-API-provider.ts
> +  export const getTotalTimeEntries = async(duration: 'ALL_TIME' | 'YEAR' | 'MONTH' | 'WEEK', person: PersonDto, year: number, week: number): Promise<WeeklyCombinedData[]> => {
done

2022-03-10 08:24 UTC, Jdallos commented on src/features/timebank/timebank-API-provider.ts
> +   *
added

2022-03-10 08:26 UTC, Jdallos commented on src/functions/schema.ts
> +
changed types to DateTime and modify types accordingly when passing to functions

2022-03-11 11:23 UTC, jarinykanen approved these changes

2022-03-14 08:46 UTC, merged